### ISSUE TITLE
Refused to get unsafe header "Content-Range"    hot-ajax-paging.html:193

### ISSUE THREAD

**Issue by GeorgiosP** [mercmobily/hot-ajax-paging#2]
_changeTotalRecords: function(e) {
        if (e.detail != this.target.lastRequest) return;

        if (this.from === '' || this.to === '') return;

        // TODO: Make calculation of range pluggable?

        var range = e.detail.xhr.getResponseHeader('Content-Range'); <-----
        if (range && range != '') this._setTotalRecords(Number(range.split('/')[1]));

      }

Code snippet where its having the issue

**Comment by mercmobily** [comment]
Which browser are you using? And which line is giving you grief exactly?

**Comment by mercmobily** [comment]
FYI this element is very actively maintained and used on a major site going into production very soon

**Comment by mercmobily** [comment]
Sorry, just saw the lline number is the message. Investigating it now. Really strange... I'd love to know what browser you are using!

**Comment by mercmobily** [comment]
I just found this:

http://stackoverflow.com/questions/39497291/refused-to-get-unsafe-header-content-length

Could you be having the same problem?

**Comment by GeorgiosP** [comment]
Hey ive been busy working on getting a site into production im using chrome
on a Windows machine in a local development environment

**Comment by mercmobily** [comment]
But... are you getting hot-ajax-paging from a CDN? Please have a look at the SO link and let us know!

**Comment by GeorgiosP** [comment]
Its getting the data from a hosted API

**Comment by GeorgiosP** [comment]
https://jsonplaceholder.typicode.com/users

I'm using this dummy data for now

**Comment by mercmobily** [comment]
I really think it's a CORS issue. Can you try and get data from your local server? Or getting your local server to fetch them and pass them through to you? (That's what should be happening anyway...)

**Comment by GeorgiosP** [comment]
Ok I'm not 100% on the HTTP protocol i'm assuming the request is being blocked because essentially the headers do not match? clarify if i'm understanding this incorrectly? Thanks!

**Comment by mercmobily** [comment]
Your issue is happening because Javascript is not letting you see the headers of the request you made, since it came from a host that differs to the one the actual page came from. Headers are needed for the pager to work. In fact, you need the server to set specific headers in order for the pager to know what data it's actually displaying...
